version: "3.8"
services:
  app:
      build:
        context: ./
        dockerfile: Dockerfile
      stdin_open: true
      ports:
        - 5173:5173
      volumes:
        - .:/usr/src/app:cached
        - /usr/src/app/node_modules
      tty: true